import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: { 
    default: "Skills-e-learning",
    template: "%s | Skills-e-learning"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
        </header>
        {children}
        </body>
    </html>
  );
}
